version: "3.1"
services:
  cdda-web:
    build: .
    image: cdda-web
    container_name: cdda
    restart: unless-stopped
    ports:
      - 50505:80
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "2"
networks:
  default:
    external:
      name: yellowgg2-subnet
